metadata.format.version = "1.1"

[versions]
minestom = "f13a7b49fa"
zstd = "1.5.5-3"

[libraries]
minestom = { group = "dev.hollowcube", name = "minestom-ce", version.ref = "minestom" }
zstd = { group = "com.github.luben", name = "zstd-jni", version.ref = "zstd" }
